Added Material Ocean theme
gadenbuie/rsthemes pull request #42
Opened 2020-12-11 03:12 UTC by lusignan

2020-12-11 05:03 UTC, gadenbuie approved these changes
Thanks, this is a really nice theme! I hope the process of putting it together was a little easier with the `rstheme()` function.

Can you please leave a comment in the PR with the original creator of the Material Ocean palette and a link to their site so that I can add it to the documentation.

2020-12-11 14:39 UTC, lusignan commented
The [Material Ocean](https://material-theme.site) palette was created by [Mattia Astorino](https://github.com/equinusocio)

2020-12-11 14:44 UTC, gadenbuie requested changes
One last little detail, can you change the lines below to use either the `mix()` or `transparentize()` SASS functions? Once that's done I can easily add the rest of the material themes by changing the base colors.

You can commit a new version of the R file or you could leave the changes in replies to the comments, whatever is easier for you.

2020-12-11 14:44 UTC, gadenbuie commented on inst/templates/material-ocean.R
> +  ui_selection                      = "#1F2233",
Use `mix()` or `transparentize()` here

2020-12-11 14:44 UTC, gadenbuie commented on inst/templates/material-ocean.R
> +  ui_gutter_foreground              = "#242937",
`mix()` or `transparentize()`

2020-12-11 14:44 UTC, gadenbuie commented on inst/templates/material-ocean.R
> +  rmd_href                          = "#e9436f",
`mix()` or `transparentize()`

2020-12-11 16:18 UTC, lusignan commented on inst/templates/material-ocean.R
> +  ui_selection                      = "#1F2233",
Do you mean for each of these chunks of 4 lines or just for the ones with a hex code instead of a color from the defined palette? If the latter I've made the change, along with some other fixes, and can commit the R file. If the former, I intentionally left the tabs all the same background color with the only difference for active tabs being the foreground text and line of color to mimic the flat look of VS Code.

2020-12-11 16:22 UTC, gadenbuie commented on inst/templates/material-ocean.R
> +  ui_selection                      = "#1F2233",
Yes, just replace the hex code with a predefined color or a function that uses a predefined color. The other lines are just GitHub trying to be helpful and show some context.

2020-12-11 16:23 UTC, gadenbuie commented on inst/templates/material-ocean.R
> +  ui_selection                      = "#1F2233",
The advantage of using predefined colors is that you or I can use the same code but swap out the colors in the `$baseXX` variables (and probably one or two other very minor tweaks) and end up with all 5 of the Material themes.

2020-12-11 16:25 UTC, gadenbuie commented on inst/templates/material-ocean.R
> +  ui_selection                      = "#1F2233",
Oh and I like the tabs flat tabs too! I updated the theme a little to move the selected tab indicator to the bottom to match the theme. There were a few other little tweaks I made on the `material-ocean.R` file so you may want to check that they don't conflict with the other updates you want to add.

2020-12-13 21:00 UTC, lusignan commented
Ayu theme created by [Ike Ku](https://github.com/dempfi/ayu)
[Dracula](https://draculatheme.com) theme created by [Zeno Rocha](https://github.com/zenorocha)

2020-12-20 04:29 UTC, closed without merging